version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=secret
    depends_on:
      - db
    command:
      - start-dev

  db:
    image: postgres:13
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=secret
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  # Your app (example with a simple web application)
#  myapp:
#    image: your-app-image  # Замените на ваш образ приложения
#    container_name: your-app
#    environment:
#      - DATABASE_URL=jdbc:postgresql://db:5432/keycloak
#      - DATABASE_USER=keycloak
#      - DATABASE_PASSWORD=secret
#    depends_on:
#      - db
#    ports:
#      - "8081:8080"

volumes:
  keycloak-db-data:
    driver: local